/**
 * ForeignPatentAdvencedSearchServicePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package kr.or.kipris.plus;

public interface ForeignPatentAdvencedSearchServicePortType extends java.rmi.Remote {
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray detailsDescriptionSearch(java.lang.String detailsDescription, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray ftermSearch(java.lang.String fterm, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray internationalOpenNumberSearch(java.lang.String internationalOpenNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray freeSearch(java.lang.String free, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray claimExtendSearch(java.lang.String claimExtend, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray applicationdateSearch(java.lang.String applicationdate, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray applicationNumberSearch(java.lang.String applicationNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public void setForeignPatentItemSearchService(kr.or.kipris.plus.webservice.services.xsd.ForeignPatentItemSearchService foreignPatentItemSearchService) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray usPatentDocumentSearch(java.lang.String usPatentDocument, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray agentsSearch(java.lang.String agents, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray openNumberSearch(java.lang.String openNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray inventorsSearch(java.lang.String inventors, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray advancedSearch(kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.FpatBeanItem fpatBean) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray registerNumberSearch(java.lang.String registerNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray upcSearch(java.lang.String upc, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray foreignRefNumberSearch(java.lang.String foreignRefNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray epcSearch(java.lang.String epc, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray otherRefSearch(java.lang.String otherRef, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray publishrDateSearch(java.lang.String publishrDate, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray priorityDateSearch(java.lang.String priorityDate, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray ipcSearch(java.lang.String ipc, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray abstractSearch(java.lang.String abstracts, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray fieldSearch(java.lang.String field, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray internationalApplicationDateSearch(java.lang.String internationalApplicationDate, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray publishrNoSearch(java.lang.String publishrNo, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray priorityNumberSearch(java.lang.String priorityNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray registerDateSearch(java.lang.String registerDate, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray openDateSearch(java.lang.String openDate, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray applicantSearch(java.lang.String applicant, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray internationalApplicationNumberSearch(java.lang.String internationalApplicationNumber, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray inventionNameSearch(java.lang.String invention, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray fiSearch(java.lang.String fi, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.foreignpatentbean.xsd.SearchResultArray relationUSSearch(java.lang.String relationUS, java.lang.String collectionValues, java.lang.String currentPage, java.lang.String docsCount, java.lang.String sortState, java.lang.String sortField) throws java.rmi.RemoteException;
}
