/**
 * PatentAdvancedSearchServicePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package kr.or.kipris.plus;

public interface PatentAdvancedSearchServicePortType extends java.rmi.Remote {
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray itemTLSearch(java.lang.String inventionTitle, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray internationalOpenDateSearch(java.lang.String internationOpenDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray registrationNumberSearch(java.lang.String registerNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray internationalOpenNumberSearch(java.lang.String internationOpenNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray freeSearch(java.lang.String word, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray agentSearch(java.lang.String agent, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray inventorSearch(java.lang.String inventors, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray applicationNumberSearch(java.lang.String applicationNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray itemCLSearch(java.lang.String claimScope, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray openNumberSearch(java.lang.String openNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray advancedSearch(kr.or.kipris.plus.webservice.services.patentbean.xsd.CategorySearchQuery categorySearchQuery, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray itemABSearch(java.lang.String astrtCont, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray applicationDateSearch(java.lang.String applicationDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray registrationDateSearch(java.lang.String registerDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray priorityDateSearch(java.lang.String priorityApplicationDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray ipcSearch(java.lang.String ipcNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray rightHolerSearch(java.lang.String rightHoler, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray internationalApplicationDateSearch(java.lang.String internationalApplicationDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray priorityNumberSearch(java.lang.String priorityApplicationNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray publicationNumberSearch(java.lang.String publicationNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray internationalApplicationNumberSearch(java.lang.String internationalApplicationNumber, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray openDateSearch(java.lang.String openDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray applicantNameSearch(java.lang.String applicant, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
    public kr.or.kipris.plus.webservice.services.patentbean.xsd.AdvancedSearchArray publicationDateSearch(java.lang.String publicationDate, java.lang.Integer docsStart, java.lang.Integer docsCount, java.lang.Boolean patent, java.lang.Boolean utility, java.lang.String lastvalue, java.lang.String sortSpec, java.lang.Boolean descSort) throws java.rmi.RemoteException;
}
